Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -15,19 +15,29 @@ jobs:
         uses: actions/download-artifact@v4.1.8
         with:
           name: ${{ inputs.filename }}
-      
-      - name: Read file content
-        id: read_file
-        run: |
-          content=$(cat "${{ inputs.filename }}")
-          echo "content=$content" >> $GITHUB_ENV
 
       - name: Update Gist
         run: |
-          curl -L \
-              -X PATCH \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${{ secrets.ACCOUNT_TOKEN_GIST }}" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              https://api.github.com/gists/${{ env.TARGET_GIST_ID }} \
-              -d "{\"files\":{\"${{ inputs.filename }}\":{\"content\": \"${{ env.content }}\"}}}"
+          content=$(cat "${{ inputs.filename }}")
+          echo "$content" | cut -c 1-100
+          
+          # 使用 jq 处理 JSON 数据
+          json_data=$(jq -n --arg filename "${{ inputs.filename }}" --arg content "$content" \
+            '{files: {($filename): {content: $content}}}')
+          
+          response=$(curl -L \
+            -X PATCH \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.ACCOUNT_TOKEN_GIST }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -d "$json_data" \
+            https://api.github.com/gists/${{ env.TARGET_GIST_ID }})
+          
+          # 检查 curl 的返回状态
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to update Gist."
+            echo "$response"
+            exit 1
+          fi
+          
+          echo "Gist updated successfully: $response"
